import 'dotenv/config';

export const config = {
  serverless: process.env.VERCEL === '1',
  port: Number(process.env.PORT) || 3333,
  frontendUrl: process.env.FRONTEND_URL || 'http://localhost:5173',
  actionCronSecret: process.env.ACTIONS_CRON_SECRET || '',
  customSourcesUrl: process.env.CUSTOM_SOURCES_URL || '',
  pythonCommand: process.env.PYTHON_COMMAND || 'python',
  ollamaUrl: process.env.OLLAMA_URL || 'http://localhost:11434',
  ollamaModel: process.env.OLLAMA_MODEL || 'qwen3:4b',
  analysisProvider: String(process.env.ANALYSIS_PROVIDER || 'auto').toLowerCase(),
  llamaCppUrl: process.env.LLAMA_CPP_URL || 'http://localhost:8080',
  llamaCppModel: process.env.LLAMA_CPP_MODEL || 'Qwen3-4B-Q4_K_M.gguf',
  githubToken: process.env.GITHUB_TOKEN || '',
  githubRepository: process.env.GITHUB_REPOSITORY || 'eb9101580-oss/informer-tributario',
  subscriptionEncryptionKey: process.env.SUBSCRIPTIONS_ENCRYPTION_KEY || '',
  trackedActionsEncryptionKey: process.env.TRACKED_ACTIONS_ENCRYPTION_KEY || process.env.SUBSCRIPTIONS_ENCRYPTION_KEY || '',
  datajudApiKey: process.env.DATAJUD_API_KEY || '',
  datajudBaseUrl: process.env.DATAJUD_BASE_URL || 'https://api-publica.datajud.cnj.jus.br',
  resendApiKey: process.env.RESEND_API_KEY || '',
  emailFrom: process.env.ALERTS_FROM_EMAIL || 'Informer Tributário <onboarding@resend.dev>',
  emailThreshold: Math.max(8, Number(process.env.ALERTS_MIN_SCORE) || 8),
  ollamaTimeoutMs: Math.max(60000, Number(process.env.OLLAMA_TIMEOUT_MS) || 600000),
  llamaCppTimeoutMs: Math.max(60000, Number(process.env.LLAMA_CPP_TIMEOUT_MS) || 600000),
  ollamaMaxInputCharacters: Math.max(2000, Number(process.env.OLLAMA_MAX_INPUT_CHARS) || 5000),
  monitorEnabled: process.env.VERCEL !== '1' && process.env.MONITOR_ENABLED !== 'false',
  monitorIntervalMinutes: Math.max(15, Number(process.env.MONITOR_INTERVAL_MINUTES) || 360),
  monitorMaxAnalyses: Math.max(0, Number(process.env.MONITOR_MAX_ANALYSES_PER_RUN) || 2),
  monitorFastPublish: process.env.MONITOR_FAST_PUBLISH === 'true',
  monitorFastPublishPerRun: Math.max(0, Number(process.env.MONITOR_FAST_PUBLISH_PER_RUN) || 20),
  monitorLookbackDays: Math.min(2, Math.max(1, Number(process.env.MONITOR_LOOKBACK_DAYS) || 2)),
  monitorInitialDelayMs: Math.max(5000, Number(process.env.MONITOR_INITIAL_DELAY_MS) || 15000),
};
